applications:
  express:
    type: 'nodejs:22'

    web:
      commands:
        start: make
      
      locations:
        '/':
          root: ''
          passthru: true

    hooks:
      build: make depends

    relationships: 
      mongo:

services:
  mongo:
    type: 'mongodb-enterprise:7.0'