applications:
  express:
    type: 'nodejs:22'

    web:
      commands:
        start: make
      
      locations:
        '/':
          root: ''
          passthru: true

    hooks:
      build: make depends

services:
  mongo:
    type: mongodb:7.0